baseURL = 'http://joseph-street-fashion-pemda3.vercel.app/'
languageCode = 'en-us'
title = 'Joseph Street Fashion Pemda'

paginate = 12

[params]
    description = "The Fashion Store"
    dateFormat= "Jan 2, 2023"
    author = "Daddy Ananta"
    keywords = "fashion, store, medan, trends, sepatu, sandal"
[taxonomies]
    category = "categories"
    author = "authors"

[[menu.main]]
    name = "About Me"
    url = "/about/"
    weight = 1

[sitemap]
changefreq = "monthly"
priority = 0.5


[outputs]
home = ["HTML", "JSON"]
