baseURL = 'http://https://joseph-street-fashion-pemda.vercel.app/'
languageCode = 'en-us'
title = 'Joseph Street Fashion Pemda'

paginate = 12

[params]
    description = "The Fashion Store"
    dateFormat= "Jan 2, 2006"
[taxonomies]
    category = "categories"
    author = "authors"

[[menu.main]]
    name = "About Me"
    url = "/about/"
    weight = 1

[outputs]
home = ["HTML", "JSON"]
